schools = [
    "ASU",
    "Amherst",
    "Boston College",
    "Boston Univ.",
    "Brandeis",
    "Brown",
    "Caltech",
    "Case Western",
    "CMU",
    "Colorado School of Mines",
    "Colorado State",
    "Columbia",
    "Cornell",
    "CU Boulder",
    "CU Denver",
    "Dartmouth",
    "Duke",
    "Emory",
    "Florida State",
    "George Washington",
    "Georgetown",
    "Georgia Tech",
    "Harvard",
    "Howard",
    "Illinois Inst. of Technology",
    "Indiana Univ. Bloomington",
    "Iowa State",
    "Johns Hopkins",
    "Lehigh",
    "McGill",
    "Michigan State",
    "Minerva",
    "Missouri Univ. of Science & Technology",
    "MIT",
    "North Carolina State",
    "Northeastern",
    "Northwestern",
    "Notre Dame",
    "NYU",
    "Ohio State",
    "Oregon State",
    "Penn State",
    "Princeton",
    "Purdue",
    "RPI",
    "Rice",
    "Rutgers",
    "Saint Louis",
    "Spelman",
    "Stanford",
    "Stony Brook",
    "SUNY Buffalo",
    "Swarthmore",
    "Texas A&M",
    "The New School",
    "Tufts",
    "Tulane",
    "UC Berkeley",
    "UC Davis",
    "UC Irvine",
    "UC Merced",
    "UC Riverside",
    "UC San Diego",
    "UC Santa Barbara",
    "UC Santa Cruz",
    "UCLA",
    "UIUC",
    "UMass Amherst",
    "UMass Boston",
    "UMCP",
    "UMich Ann Arbor",
    "UNC Chapel Hill",
    "Univ. of Alaska Fairbanks",
    "Univ. of Arizona",
    "Univ. of Calgary",
    "Univ. of Chicago",
    "Univ. of Connecticut",
    "Univ. of Delaware",
    "Univ. of Florida",
    "Univ. of Georgia",
    "Univ. of Hawai'i at Manoa",
    "Univ. of Illinois, Chicago",
    "Univ. of Iowa",
    "Univ. of Kansas",
    "Univ. of Miami",
    "Univ. of Minnesota, Twin Cities",
    "Univ. of Missouri, Columbia",
    "Univ. of New Mexico",
    "Univ. of Pittsburgh",
    "Univ. of Rochester",
    "Univ. of South Florida",
    "Univ. of Tennessee, Knoxville",
    "Univ. of Utah",
    "Univ. of Virginia",
    "Univ. of Washington",
    "UPenn",
    "USC",
    "UT Austin",
    "UT Dallas",
    "UW Madison",
    "Vanderbilt",
    "Virginia Tech",
    "Wake Forest",
    "Washington State",
    "WashU St. Louis",
    "Waterloo",
    "Wayne State",
    "Wesleyan",
    "Yale",
    "Other",
]

graduation_times = [
    "2025, Winter",
    "2025, Spring",
    "2026, Winter",
    "2026, Spring",
    "2027, Winter",
    "2027, Spring",
    "2028, Winter",
    "2028, Spring",
    "2029, Winter",
    "2029, Spring",
]

majors = [
  "Business Administration and Management",
  "Nursing",
  "Psychology",
  "Biology",
  "Education",
  "Engineering",
  "Computer Science",
  "Communication and Media Studies",
  "Political Science and Government",
  "Accounting",
  "Economics",
  "English",
  "History",
  "Sociology",
  "Marketing",
  "Finance",
  "Liberal Arts",
  "Public Health",
  "Environmental Science",
  "Mathematics",
  "Chemistry",
  "International Relations",
  "Anthropology",
  "Journalism",
  "Physics",
  "Graphic Design",
  "Philosophy and Religious Studies",
  "Architecture",
  "Geography",
  "Biomedical Engineering",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Chemical Engineering",
  "Civil Engineering",
  "Data Science",
  "Information Science",
  "Aerospace Engineering",
  "Statistics",
  "UI/UX",
  "Astronomy",
  "Material Science",
  "Systems Engineering",
  "Other"
]

skills = [
  "ABAP",
  "ABC",
  "ActionScript",
  "Ada",
  "Amazon Echo",
  "Amazon Web Services (AWS)",
  "Android",
  "Angular",
  "AppleScript",
  "Arduino",
  "Assembly",
  "Automator",
  "Awk",
  "Bash/Shell",
  "Basic",
  "Blockchain",
  "Bourne Shell",
  "Bro",
  "C",
  "C#",
  "C++",
  "CAD Design",
  "Cassandra",
  "Chatbots",
  "Clojure",
  "COBOL",
  "CoffeeScript",
  "Common Lisp",
  "Computer Vision",
  "Coq",
  "Cordova",
  "Cryptography",
  "C Shell",
  "CSS",
  "CUDA",
  "D",
  "Dart",
  "Data Analytics",
  "Data Modeling",
  "Data Warehousing",
  "Deep Learning",
  "Device Drivers",
  "Distributed Systems",
  "Django",
  "Docker",
  "DynamoDB",
  "Eclipse",
  "Elasticsearch",
  "Elastic Stack (ELK)",
  "Elixir",
  "Emacs Lisp",
  "Embedded Linux",
  "Erlang",
  "Ethereum",
  "ETL",
  "Express",
  "F#",
  "Firebase",
  "Firmware",
  "Flask",
  "Flutter",
  "Fortran",
  "FoxPro",
  "Git",
  "GNU Octave",
  "Go",
  "Google App Engine",
  "Google Cloud",
  "Google Home",
  "Google Web Toolkit",
  "GPU Programming",
  "GraphQL",
  "Groovy",
  "gRPC",
  "Hack",
  "Hadoop",
  "Haskell",
  "HBase",
  "Heroku",
  "Hibernate",
  "Hive",
  "HTML",
  "Hyperledger",
  "IBM Cloud/Watson",
  "IBM Db2",
  "Idris",
  "IIS",
  "Image Processing",
  "Information Security",
  "Internet of Things (IoT)",
  "iOS",
  "Java",
  "JavaScript",
  "Jenkins",
  "jQuery",
  "Julia",
  "JUnit",
  "Kafka",
  "Keras",
  "Kibana",
  "Korn Shell",
  "Kotlin",
  "Kubernetes",
  "Less",
  "Linux",
  "Lisp",
  "Logstash",
  "Lua",
  "Lucene",
  "M4",
  "Machine Learning",
  "MacOS",
  "Maple",
  "MariaDB",
  "Mathematica",
  "MATLAB",
  "Maven",
  "Memcached",
  "Mercurial",
  "Microcontrollers",
  "Microservices",
  "Microsoft Azure",
  "ML",
  "MongoDB",
  "MS SQL",
  "MUMPS",
  "MySQL",
  "Natural Language Processing",
  "Neo4j",
  ".NET Core",
  "Nginx",
  "Node.js",
  "Objective-C",
  "OCaml",
  "Oculus",
  "OpenCL",
  "OpenCV",
  "OpenGL",
  "Oracle",
  "Pascal",
  "Perl",
  "PHP",
  "PL/SQL",
  "PostgreSQL",
  "PowerScript",
  "PowerShell",
  "Processing",
  "Protobuf",
  "Puppet",
  "Python",
  "R",
  "RabbitMQ",
  "Racket",
  "Raspberry Pi",
  "RDS/Aurora",
  "React",
  "React Native",
  "Redis",
  "Redshift",
  "Reinforcement learning (RL)",
  "Riak",
  "Ruby",
  "Ruby on Rails",
  "Rust",
  "SAS",
  "SASS",
  "Scala",
  "Scheme",
  "Scratch",
  "SCSS",
  "Search",
  "sed",
  "Serverless",
  "Smalltalk",
  "Smarty",
  "Software Architecture",
  "Software Security",
  "Solidity",
  "Solr",
  "Spark",
  "Spring",
  "Spring Framework",
  "SQL",
  "SQLite",
  "SQL Server",
  "Standard ML",
  "Stellar",
  "Svelte",
  "Swift",
  "Tcl",
  "TCP/IP",
  "TensorFlow",
  "Tex",
  "Theano",
  "Tomcat",
  "Torch/PyTorch",
  "TypeScript",
  "Unity",
  "Unix",
  "Unreal Engine",
  "VBScript",
  "Verilog",
  "VHDL",
  "Visual Basic",
  "Vue.js",
  "WebLogic",
  "WebVR",
  "Windows",
  "Xamarin",
  "XML",
  "XQuery",
  "XSLT",
  "yacc",
  "Z shell",
  "3DS Max",
  "Adobe After Effects",
  "Adobe Premiere",
  "Adobe XD",
  "Autodesk Maya",
  "Blender",
  "Branding",
  "Cinema4D",
  "Design systems",
  "Figma",
  "Growth design",
  "Illustrator",
  "Marketing design",
  "Packaging",
  "Photoshop",
  "Prototyping",
  "Rhino",
  "Sketch",
  "Wireframing",
  "Zbrush",
  "aCGH",
  "Bacteria culturing",
  "Bacteria engineering",
  "Biochemistry",
  "Bioinformatics",
  "Biology",
  "Biophysics",
  "Biostatistics",
  "Biotechnology",
  "Cell biology",
  "Chemistry",
  "Chimera",
  "CRISPR",
  "DNA synthesis",
  "Drug development",
  "Electrochemistry",
  "Enzymatic assays",
  "Experimental therapeutics",
  "FACS",
  "Fermentation",
  "Flow cytometry",
  "Gene sequencing",
  "Gene synthesis",
  "Genome engineering",
  "Genomics",
  "Immunology",
  "Material science",
  "Medicinal chemistry",
  "Membranes",
  "Metabolic diseases",
  "Microbiology",
  "Microfluidics",
  "MLPA",
  "Molecular biology",
  "Molecular design",
  "Molecular Operating Environment (MOE)",
  "Neuropharmacology",
  "Neuroscience",
  "Next generation sequencing",
  "Pharmacology",
  "Phenotyping",
  "Phylogenetics",
  "Protein engineering",
  "PyMOL",
  "Quantitative biology",
  "Rosetta",
  "Sanger",
  "Schrodinger",
  "Sequence analysis",
  "Synaptic imaging",
  "Virology",
  "Virus engineering",
  "Wet lab"
]
